import test from "ava"
import CircularJSON from "circular-json"
import {Trie} from "../dist/mathconv/trie"

const str = o => CircularJSON.stringify(o)
const r = String.raw

import a from "../dist/mathconv/asciimath"
//console.log("asciimath:", str(a))

test('Trie inf+i?n?i?t?y works', t => {
  const trie = new Trie()
  trie.insert("inf+i?n?i?t?y", 1)
  t.deepEqual(trie.match("infinity"), {value: 1, match: "infinity"})
  t.deepEqual(trie.match("infy"), {value: 1, match: "infy"})
  t.deepEqual(trie.match("infffity"), {value: 1, match: "infffity"})
  t.true(trie.match("inffofity") === null)
  t.true(trie.match("inf") === null)
  trie.insert("inf+i?n?i?t?y?", 2)
  t.deepEqual(trie.match("inf"), {value: 2, match: "inf"})
  t.deepEqual(trie.match("infinity"), {value: 2, match: "infinity"}) // FILO
})

test('Trie hel(lo) works', t => { // hel(la|(lo)+)?
  const trie = new Trie()
  trie.insert(r`hel(lo)`, 1)
  t.deepEqual(trie.match("hello"), {value: 1, match: "hello"})
})

test('Trie hel(lo)?ya works', t => { // hel(la|(lo)+)?
  const trie = new Trie()
  trie.insert(r`hel(lo)?ya`, 1)
  t.deepEqual(trie.match("helya"), {value: 1, match: "helya"})
  t.deepEqual(trie.match("helloya"), {value: 1, match: "helloya"})
  t.true(trie.match("hellya") === null)
})

test('Trie hel(lo)+ya works', t => { // hel(la|(lo)+)?
  const trie = new Trie()
  trie.insert(r`hel(lo)+ya`, 1)
  //console.log(str(trie))
  t.deepEqual(trie.match("helloya"), {value: 1, match: "helloya"})
  t.deepEqual(trie.match("helloloya"), {value: 1, match: "helloloya"})
  t.deepEqual(trie.match("hellolololoya"), {value: 1, match: "hellolololoya"})
  t.true(trie.match("hellollya") === null) // should NOT match
  t.true(trie.match("helloolya") === null) // caused endless loop before
  t.true(trie.match("helya") === null)
})

test('Trie a[0-9]*z works', t => {
  let trie = new Trie()
  trie.insert(r`a[0-9]*z`, 1)
  t.deepEqual(trie.match("a2017z"), {value: 1, match: "a2017z"})
  trie = new Trie()
  trie.insert(r`a[0-9]*z?`, 1) // a2?z? does work
  t.deepEqual(trie.match("a"), {value: 1, match: "a"})
  t.deepEqual(trie.match("a2z"), {value: 1, match: "a2z"})
  t.deepEqual(trie.match("a2"), {value: 1, match: "a2"})
  t.deepEqual(trie.match("a"), {value: 1, match: "a"})
  t.deepEqual(trie.match("a90000"), {value: 1, match: "a90000"})
})

test('Trie [0-9]+(.[0-9]+)? works', t => {
  const trie = new Trie()
  trie.insert(r`[0-9]+(.[0-9]+)?`, 1)
  t.deepEqual(trie.match("21.91"), {value: 1, match: "21.91"})
  t.deepEqual(trie.match("21"), {value: 1, match: "21"})
  t.deepEqual(trie.match("21."), {value: 1, match: "21"})
})

test('Trie named groups work', t => {
  const trie = new Trie()
  trie.define("FLOAT", r`[0-9]+(.[0-9]+)?`)
  trie.insert("a{FLOAT}?", 1)
  t.deepEqual(trie.match("a4.2"), {value: 1, match: "a4.2"})
  t.deepEqual(trie.match("a4."), {value: 1, match: "a4"})
  t.deepEqual(trie.match("a"), {value: 1, match: "a"})
})

test('Trie backslash handling works', t => {
  let trie = new Trie()
  trie.insert(r`a\{FLOAT}?`, 1)
  t.deepEqual(trie.match("a{FLOAT"), {value: 1, match: "a{FLOAT"})
  trie = new Trie()
  trie.define("FLOAT", r`[0-9]+(.[0-9]+)?`)
  trie.insert(r`a\\{FLOAT}?`, 1)
  t.deepEqual(trie.match("a\\2.22"), {value: 1, match: "a\\2.22"})
  t.deepEqual(trie.match("a\\"), {value: 1, match: "a\\"})
})

test('Trie {GREEK_LETTER}{WS}*(+|-){WS}*{GREEK_LETTER} works', t => {
  let trie = new Trie()
  trie.define("WS", "[ \t\r\n\f]")
  trie.define("GREEK_LETTER", Object.keys(a.TOKENS.GREEK_LETTER).join("|"))
  trie.insert("{GREEK_LETTER}(+|-){GREEK_LETTER}", 1)
  t.deepEqual(trie.match("α+α"), {value: 1, match: "α+α"})
  t.deepEqual(trie.match("ζ+Π"), {value: 1, match: "ζ+Π"})
  trie = new Trie()
  trie.insert("[a-c][0-2]?[d-f]?[3-5]?[g-h]", 1)
  t.deepEqual(trie.match("ag"), {value: 1, match: "ag"})
  t.true(trie.match("a") === null)
  trie.insert("[a-c][0-2]?[d-f]?[3-5]?[g-h]?", 2)
  t.deepEqual(trie.match("a"), {value: 2, match: "a"})
  t.deepEqual(trie.match("ag"), {value: 2, match: "ag"})
})

test('Trie capture-groups work (1)', t => {
  let trie = new Trie()
  trie.define("WS", "[ \t\r\n\f]")
  trie.define("OP", r`[+\-]`)
  trie.define("VAR", "[a-e]+")
  trie.insert("{left:VAR}+{operator:OP}{right:VAR}+", 1)
  console.log("before", str(trie))
  t.deepEqual(trie.match("a+b"), {left: "a", operator: "+", right: "b"})
  t.deepEqual(trie.match("aa+ab"), {left: "aa", operator: "+", right: "ab"})
  trie = new Trie()
  trie.define("WS", "[ \t\r\n\f]")
  trie.define("OP", r`[+\-]`)
  trie.define("VAR", "[a-e]+")
  trie.insert("{left:VAR}*{operator:OP}{right:VAR}*", 1)
  console.log("after", str(trie))
  //t.deepEqual(trie.match("+"), {operator: "+"}) // FIXME
})

test('Trie capture-groups work (2)', t => {
  let trie = new Trie()
  trie.define("VAR", "[a-e]+")
  trie.insert("{word:VAR}(,{word:VAR})*", 1)
  //console.log(str(trie))
  t.deepEqual(trie.match("a,b,abab,c,d"), {"word": ["a", "b", "abab", "c", "d"]})
})

test('Trie groups *+? works', t => {
  let trie = new Trie()
  trie.insert(r`a(bc)d`, 1)
  console.log("variant0", str(trie))
  t.deepEqual(trie.match("abcd"), {value: 1, match: "abcd"})
  t.true(trie.match("a") === null)
  t.true(trie.match("ab") === null)
  t.true(trie.match("ad") === null)
  t.true(trie.match("abc") === null)
  t.true(trie.match("abcbcd") === null)
  trie = new Trie()
  trie.insert(r`a(bc)?d`, 1)
  console.log("variant1", str(trie))
  t.deepEqual(trie.match("abcd"), {value: 1, match: "abcd"})
  t.deepEqual(trie.match("ad"), {value: 1, match: "ad"})
  t.true(trie.match("a") === null)
  t.true(trie.match("ab") === null)
  t.true(trie.match("abc") === null)
  t.true(trie.match("abcbcd") === null)
  trie = new Trie()
  trie.insert(r`a(ab)?d`, 1)
  console.log("variant1.1", str(trie))
  t.deepEqual(trie.match("aabd"), {value: 1, match: "aabd"})
  t.deepEqual(trie.match("ad"), {value: 1, match: "ad"})
  t.true(trie.match("a") === null)
  t.true(trie.match("aababd") === null)
  trie = new Trie()
  trie.insert(r`a(bc)*d`, 1)
  console.log("variant2", str(trie))
  t.deepEqual(trie.match("abcd"), {value: 1, match: "abcd"})
  t.deepEqual(trie.match("abcbcbcd"), {value: 1, match: "abcbcbcd"})
  t.deepEqual(trie.match("ad"), {value: 1, match: "ad"})
  t.true(trie.match("a") === null)
  t.true(trie.match("ab") === null)
  t.true(trie.match("abc") === null)
  trie = new Trie()
  trie.insert(r`a(ab)*d`, 1)
  console.log("variant2.1", str(trie))
  t.deepEqual(trie.match("aabd"), {value: 1, match: "aabd"})
  t.deepEqual(trie.match("aababd"), {value: 1, match: "aababd"})
  t.deepEqual(trie.match("ad"), {value: 1, match: "ad"})
  t.true(trie.match("a") === null)
  t.true(trie.match("aa") === null)
  t.true(trie.match("aab") === null)
  trie = new Trie()
  trie.insert(r`a(bc)+d`, 1)
  console.log("variant3", str(trie))
  t.deepEqual(trie.match("abcd"), {value: 1, match: "abcd"})
  t.deepEqual(trie.match("abcbcbcd"), {value: 1, match: "abcbcbcd"})
  t.true(trie.match("a") === null)
  t.true(trie.match("ab") === null)
  t.true(trie.match("abc") === null)
  t.true(trie.match("ad") === null)
  trie = new Trie()
  trie.insert(r`a(ab)+d`, 1)
  console.log("variant3.1", str(trie))
  t.deepEqual(trie.match("aabd"), {value: 1, match: "aabd"})
  t.deepEqual(trie.match("aababd"), {value: 1, match: "aababd"})
  t.true(trie.match("a") === null)
  t.true(trie.match("aa") === null)
  t.true(trie.match("aab") === null)
  t.true(trie.match("ad") === null)
})
