export default {
  TOKENS: {
    LEFT_BRACKET: {
      '⟨': '\(:|<<|langle',
      '(': '(',
      '[': '[',
      '{': '{',
      '⌊': 'lfloor',
      '⌈': 'lceiling',
    },
    RIGHT_BRACKET: {
      '⟩': ':\)|>>|rangle',
      ')': ')',
      ']': ']',
      '}': '}',
      '⌋': 'rfloor',
      '⌉': 'rceiling',
    },
    BINARY_OPERATOR_SYMBOL: {
      '+': '+',
      '−': '-',
      '±': '\+\-|pm',
      '÷': '-:|div',
      '⋆': '\*\*\*|star',
      '∗': '\*\*|ast',
      '⋅': '\*|cdot',
      '/': '\/\/',
      '\\': '\\\\',
      '⋈': 'bowtie',
      '⋉': 'ltimes',
      '×': 'xx|times',
      '∘': '@|circ',
      '⊕': 'o+|xor|oplus',
      '⊗': 'ox|otimes',
      '⊙': 'o.|odot',
      '∩': 'cap',
      '∪': 'cup',
      '=': '=',
      '≠': '!=|ne',
      '≔': ':=',
      '⪯': '-<=|preceq',
      '≺': '-<|prec',
      '≤': '<=|le|lt=|leq',
      '&lt;': '<|lt',
      '⋊': '><\|rtimes',
      '≥': '>=|ge|gt=|geq',
      '⪰': '>-=|succeq',
      '≻': '>-|succ',
      '&gt;': '>|gt',
      '∈': 'element|in',
      '∉': '!in|!element|notin',
      '⊆': 'sub(set)?e(q)?',
      '⊂': 'sub(set)?',
      '⊇': 'sup(set)?e(q)?',
      '⊃': 'sup(set)?',
      '≡': '-=|eq(u)?(iv|als)?',
      '≌': '~=|cong',
      '≈': '~~|approx',
      '∝': 'prop(to)?',
      '∧': 'and|wedge',
      '∨': 'or|vee',
      '⇒': '=>|impl(y|ies)',
      'if': 'if',
      '⇔': '<=>|iff',
      '⊢': '\|--|vdash',
      '⊨': '\|==|models',
    },
    MISC_SYMBOL: {
      '∂': 'del|partial',
      '∇': 'grad|nabla',
      '⊥': 'bot(tom)?',
      '⊤': 'top',
      '∅': 'O\/|empty(set)?',
      '∞': 'oo|inf(inity)?',
      'ℵ': 'aleph',
      '…': '...|ldots',
      '∴': ':.|therefore',
      '∠': '\/_|angle',
      '△': '\/_\|triangle',
      '′': 'prime',
      '&nbsp;': '\\ ',
      '⌢': 'frown',
      '&nbsp;&nbsp;': 'quad',
      '&nbsp;&nbsp;&nbsp;&nbsp;': 'qquad',
      '⋯': 'cdots',
      '⋮': 'vdots',
      '⋱': 'ddots',
      '⋄': 'diamond',
      '□': 'square',
      'ℂ': 'C(C)?',
      'ℕ': 'N(N)?',
      'ℚ': 'Q(Q)?',
      'ℝ': 'R(R)?',
      'ℤ': 'Z(Z)?',
    },
    ARROW_SYMBOL: {
      '↑': 'u(p)?arr(ow)?',
      '↓': 'd(own)?arr(ow)?',
      '→': '->|r(ight)?arr(ow)?',
      '←': '<-|l(eft)?arr(ow)?',
      '↔': '<->|l(eft)?r(ight)?arr(ow)?',
      '↦': '\|->|mapsto',
      '⇒': '=>|R(ight)?arr(ow)?',
      '⇐': '<=|L(eft)?arr(ow)?',
      '⇔': '<=>|L(eft)?r(ight)?arr(ow)?',
      '↣': '>->',
      '↠': '->>',
    },
    UNARY_PREFIX_OPERATOR: {
      '∫': 'int',
      '∮': 'oint',
      'Σ': 'sum',
      'Π': 'prod',
      '⋀': 'And|Wedge|bigwedge',
      '⋁': 'Or|Vee|bigvee',
      '⋂': 'Cap|bigcap',
      '⋃': 'Cup|bigcup',
      '∀': 'forall',
      '∃': 'exists',
      'lim': 'lim',
      'Lim': 'Lim',
      'min': 'min',
      'max': 'max',
      '¬': 'not|neg',
    },
    SQRT: {
      '√': 'sqrt',
    },
    GREEK_LETTER: {
      'α': 'alpha',
      'β': 'beta',
      'χ': 'chi',
      'δ': 'delta',
      'Δ': 'Delta',
      'ε': 'eps(ilon)?',
      'η': 'eta',
      'γ': 'gamma',
      'Γ': 'Gamma',
      'ι': 'iota',
      'κ': 'kappa',
      'λ': 'lambda',
      'Λ': 'Lambda',
      'μ': 'mu',
      'ν': 'nu',
      'ω': 'omega',
      'Ω': 'Omega',
      'φ': 'phi',
      'Φ': 'Phi',
      'π': 'pi',
      'Π': 'Pi',
      'ψ': 'psi',
      'Ψ': 'Psi',
      'ρ': 'rho',
      'σ': 'sigma',
      'Σ': 'Sigma',
      'τ': 'tau',
      'ϑ': 'theta',
      'Θ': 'Theta',
      'υ': 'upsilon',
      'ξ': 'xi',
      'Ξ': 'Xi',
      'ζ': 'zeta',
    },
    STANDARD_FUNCTION_NAME: [
      'sin',
      'cos',
      'tan',
      'sinh',
      'cosh',
      'tanh',
      'cot',
      'sec',
      'csc',
      'arcsin',
      'arccos',
      'arctan',
      'coth',
      'sech',
      'csch',
      'exp',
      'log',
      'ln',
      'lg',
      'det',
      'dim',
      'mod',
      'gcd',
      'lcm',
      'lub',
      'glb',
    ]
  }
}
